---
title: "Tables"
author: "Lukas Stammler"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_height: 4
    fig_width: 5
    highlight: pygments
    theme: yeti
    code_download: false
    toc: yes
    number_sections: yes
    toc_float: yes
bibliography: book.bib
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, message = FALSE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(openintro)   # for simple areas under curve
library(patchwork)   # arrange ggplot objects
```

# Cool packages

```{r, eval=FALSE}
library(rstatix)     # t.test output as tibble 
library(stargazer)   # summary tables and regression tables
```

# Add a total row to a summarise tibble  

```{r}
## create some data ------------------------------------------------------------
shark <- tibble(
  Jahr = seq(from = 2012, to = 2021, by = 1),
  letal = c(7, 10, 3, 6, 4, 5, 4, 2, 10, 9),
  nicht.letal = c(76, 67, 70, 92, 77, 84, 64, 62, 47, 62)
) %>% 
  mutate(
    Total = letal + nicht.letal,
    Prozent.letal = (letal/Total) * 100
  )

## function to calculatie summary row ------------------------------------------
func <- function(z) if (is.numeric(z)) sum(z) else ''
sumrow <- as_tibble(lapply(shark, func))

## change values in total row --------------------------------------------------
sumrow[1] <- "Total"
sumrow[5] <- (sumrow[2]/sumrow[4]) * 100
shark.tab <- rbind(shark, sumrow) 

## format output ---------------------------------------------------------------
shark.tab %>% 
  kbl(digits = 2, caption = "Haifischattacken weltweit 2012-2021") %>% 
  kable_styling(full_width = FALSE) %>%
  row_spec(dim(shark.tab)[1], bold = T) %>% # format last row
  column_spec(1, italic = T) # format first column
```